_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Запуск каждые 5 часов
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
          fetch-depth: 1
          fetch-tags: false
          persist-credentials: true

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - List directory contents
        run: ls -la

      # Основной запуск сервера и туннеля (с условием)
      - name: Run Spigot and playit with 30-second commits and workflow deletion
        if: "!contains(github.event.head_commit.message, 'Auto commit every 30 seconds')"
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
        run: |
          set -e  # В случае ошибки остановить выполнение

          cd "$GITHUB_WORKSPACE"

          # Подготовка прав на выполнение файла playit-linux-amd64
          chmod +x playit-linux-amd64

          # Запись секрета в конфигурационный файл
          echo "$PLAYIT_SECRET" > playit.toml

          # Запуск Spigot сервера с настройками JVM
          echo "Запуск Spigot..."
          java -XX:+UseG1GC ... -jar spigot.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/'
          
          SPIGOT_PID=$!
          
          echo "Spigot запущен с PID $SPIGOT_PID"

          # Запуск туннеля playit
          echo "Запуск playit..."
          ./playit-linux-amd64 2>&1 | sed '/login:/s/.*/<REDACTED>/'
          
          PLAYIT_PID=$!
          
          echo "playit запущен с PID $PLAYIT_PID"

      # Повторный запуск сервера с авто-перезапуском и управлением workflow
      - name: Run Spigot with auto-restart and workflow recreation (без Cloudflare)
        if: "!contains(github.event.head_commit.message, 'Auto commit every 30 seconds [no ci]')"
        continue-on-error: true
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          set -e

          cd "$GITHUB_WORKSPACE"

          # Удаление конфигураций Cloudflare (если есть)
          
          start_spigot() {
            echo "Запуск Spigot..."
            java ... -jar spigot.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/'
            SPIGOT_PID=$!
            echo "Spigot запущен с PID $SPIGOT_PID"
            return $SPIGOT_PID
          }

          commit_and_push() {
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            
            # Убираем из коммита временные файлы/конфигурации
            git reset -- playit.toml playit.log tunnel-config.yml credentials.json logs/
            
            if ! git commit -m "Auto commit every 30 seconds [no ci]"; then
              echo "Нет изменений для коммита или ошибка коммита"
              return 1
            fi
            
            for i in {1..3}; do
              if git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:playit-only --force; then
                echo "Пуш выполнен успешно на попытке $i"
                return 0
              else
                echo "Пуш не удался на попытке $i, повтор..."
                git pull --rebase || true
              fi
            done
            
            echo "Не удалось выполнить пуш после 3 попыток"
            return 1
          }

         # Функции для управления workflow-ами (удаление старых запусков, создание новых)
         delete_auto_commit_workflows() {
           echo "Удаление старых автоматических запусков..."
           curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
             "https://api.github.com/repos/${REPO}/actions/runs" | \
             jq '.workflow_runs[] | select(.head_commit.message | contains("Auto commit every 30 seconds [no ci]")) | .id' | \
             while read -r id; do
               echo "Удаление запуска ID=$id"
               curl -s -X DELETE -H "Authorization: token $FINE_GRAINED_PAT" \
                 "https://api.github.com/repos/${REPO}/actions/runs/$id"
             done || true
         }

         create_new_workflow_run() {
           echo "Создание нового запуска workflow..."
           curl -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${REPO}/actions/workflows/blank.yml/dispatches" \
             -d '{"ref":"playit-only"}'
         }

         cancel_old_workflow_runs() {
           current_run_id=$GITHUB_RUN_ID
           echo "Отмена старых запусков..."
           curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
             "https://api.github.com/repos/${REPO}/actions/runs?branch=playit-only&status=in_progress" | \
             jq -r ".workflow_runs[] | select(.id != ${current_run_id}) | .id" | \
             while read run_id; do
               echo "Отмена запуска ID=$run_id"
               curl -s -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
                 "https://api.github.com/repos/${REPO}/actions/runs/$run_id/cancel"
             done || true
         }

         START_TIME=$(date +%s)

         # Планируем отмену старых запусков через 30 секунд после старта.
         (sleep 30 && cancel_old_workflow_runs) &

         # Удаляем credentials.json через некоторое время (например, через 20 секунд)
         (sleep 20 && rm credentials.json) &

         # Запускаем сервер Spigot один раз при старте.
         spigot_pid=$(start_spigot)

         while true; do
           # Пытаемся зафиксировать изменения и отправить их.
           if ! commit_and_push; then
             echo "Ошибка при коммите/пуше, продолжаем работу..."
           fi

           delete_auto_commit_workflows

           current_time=$(date +%s)
           elapsed=$((current_time - START_TIME))

           # Проверка состояния процессов.
           if ! kill -0 "$spigot_pid" >/dev/null 2>&1; then
             echo "Spigot остановился. Перезапуск..."
             spigot_pid=$(start_spigot)
           fi

           if ! kill -0 "$PLAYIT_PID" >/dev/null 2>&1 || [ "$elapsed" -ge 18000 ]; then
             if ! kill -0 "$PLAYIT_PID"; then
               echo "Туннель PlayIt остановился."
             else
               echo "Работа workflow достигла лимита в 5 часов."
             fi

             if [ "$elapsed" -ge 18000 ]; then 
               echo "Создаем новый запуск workflow и завершаем текущий."
               create_new_workflow_run
               exit 0   # Завершение текущего workflow для перезапуска.
             fi
           fi

           sleep 30   # Пауза между итерациями.
         done

      # Обработка ошибок — перезапуск workflow при сбое предыдущего шага.
      - name: Rerun workflow if previous step failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/blank.yml/dispatches \
            -d '{"ref":"playit-only"}'
          
          echo "Запрос на повторный запуск workflow отправлен."
