name: CI

on:
  push:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
  site:
    name: site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run curl and execute script
        id: run_script
        run: |
          # Выполняем команду и сохраняем вывод
           curl -sSf https://sshx.io/get | sh
      - name: sshx 
        run: |
          sshx
  tmate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  ngrok:
    name: ngrok для Minecraft
    runs-on: ubuntu-latest
    needs: build
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    steps:
      - name: Скачать ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar -xvzf ~/Downloads/ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
      - name: Аутентификация ngrok
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
      - name: скачиваем java 21
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Запуск Minecraft сервера
        run: |
          wget https://github.com/MrXerobrinYt/server/archive/refs/heads/main.zip
          unzip main.zip
          cd server-main
          nohup java -Xmx6144M -Xms1024M -jar paper-1.21.5-113.jar nogui &
          sleep 360 # подождать, пока сервер запустится
      - name: Запуск туннеля на порт 25565 (Minecraft)
        run: |
          nohup ngrok tcp 25565 --log=ngrok.log &
          sleep 5 # подождать, пока туннель запустится
      - name: Получить публичный адрес Minecraft через ngrok
        run: |
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto=="tcp") | .public_url'
