name: CI

on:
  push:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
  site:
    name: site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run curl and execute script
        id: run_script
        run: |
          # Выполняем команду и сохраняем вывод
          LINK=$(curl -sSf https://sshx.io/get | sh)
          
      - name: Execute sshx command без ссылки
        run: |
          sshx
  proxy:
    name: proxy
    runs-on: ubuntu-latest
    
    needs: build

    steps:
      - name: PROXY
        id: run_proxy
        run: |
          chmod +x /home/runner/.config/ngrok/ngrok.yml
          sudo snap install ngrok
          sudo ngrok config add-authtoken 2NcNkuFuaaEV6MbhSXHVte2vEYY_6rcGF8dqknsrwkK4Em87Y
          sudo ngrok tcp 25565
