name: CI

on:
  push:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl and execute script
        id: run_script
        run: |
          # Выполняем команду и сохраняем вывод
          LINK=$(curl -sSf https://sshx.io/get | sh)
          
      - name: Execute sshx command без ссылки
        run: |
          sshx
  proxy:
    name: proxy
    runs-on: ubuntu-latest
    
    needs: build

    steps:
      - name: PROXY
        id: run_proxy
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \| sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \&& echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \| sudo tee /etc/apt/sources.list.d/ngrok.list \&& sudo apt update \&& sudo apt install ngrok
          ngrok config 
