name: CI

on:
  push:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
  site:
    name: site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run curl and execute script
        id: run_script
        run: |
          # Выполняем команду и сохраняем вывод
           curl -sSf https://sshx.io/get | sh
      - name: sshx 
        run: |
          sshx
  proxy:
    name: proxy
    runs-on: ubuntu-latest
    steps:
      - name: Run curl and execute script
        id: run_proxy
        run: |
           sudo su
           curl -sSLf https://get.tuna.am | sh
           tuna config save-token tt_9gknu7gf87jrv54swunsya340h2shu63
           tuna http 8080
  tmate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
