name: CI

on:
  push:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
  site:
    name: site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run curl and execute script
        id: run_script
        run: |
        
          # Выполняем команду и сохраняем вывод
           curl -sSf https://sshx.io/get | sh
      - name: sshx 
        run: |
          sshx
  proxy:
    name: proxy
    runs-on: ubuntu-latest
    steps:
      - name: Run curl and execute script
        id: run_proxy
        run: |
           sudo su
           curl -sSLf https://get.tuna.am | sh
           tuna config save-token tt_9gknu7gf87jrv54swunsya340h2shu63
           tuna http 8080
  tmate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  ngrok:
    name: ngrok для Minecraft
    runs-on: ubuntu-latest
    needs: build
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    steps:
      - name: Скачать ngrok
        run: |
          wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin/
      - name: Аутентификация ngrok
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
      - name: Запуск Minecraft сервера (пример)
        run: |
          # Предположим, что у вас есть скрипт или команда запуска сервера
          # Например, запуск через screen или nohup
          # Здесь просто пример:
          nohup java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui &
          sleep 10 # подождать, пока сервер запустится
      - name: Запуск туннеля на порт 25565 (Minecraft)
        run: |
          nohup ngrok tcp 25565 --log=ngrok.log &
          sleep 5 # подождать, пока туннель запустится
      - name: Получить публичный адрес Minecraft через ngrok
        run: |
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto=="tcp") | .public_url'
