name: Minecraft Server with Ngrok and Auto-Restart

on:
  schedule:
    - cron: '0 */5 * * *'  # Каждые 5 часов
  workflow_dispatch:       # Также вручную

jobs:
  run-minecraft:
    runs-on: ubuntu-latest

    env:
      MINECRAFT_VERSION: '1.20.2'
      MINECRAFT_SERVER_JAR: 'server.jar'
      SERVER_DIR: ${{ github.workspace }}/minecraft_server
      CACHE_DIR: ${{ github.workspace }}/cache
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Проверка кода репозитория
        uses: actions/checkout@v3

      - name: Создание папки для кеша
        run: mkdir -p "$CACHE_DIR"

      - name: Установка Java (если не было кеша)
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}/java
          key: java-${{ runner.os }}-${{ env.MINECRAFT_VERSION }}
          restore-keys: |
            java-${{ runner.os }}-
        continue-on-error: true

      - name: Установка Java (если не было кеша)
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          mkdir -p "$CACHE_DIR/java"

      - name: Скачивание файла сервера Minecraft, если не закеширован
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}/minecraft_server.jar
          key: minecraft-${{ env.MINECRAFT_VERSION }}
          restore-keys: |
            minecraft-
        id: cache-minecraft

      - name: Скачивание файла сервера Minecraft (если не было кеша)
        if: steps.cache-minecraft.outputs.cache-hit != 'true'
        run: |
          mkdir -p "$SERVER_DIR"
          cd "$SERVER_DIR"
          
          VERSION_URL=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r --arg VERSION "$MINECRAFT_VERSION" '.versions[] | select(.id==$VERSION) | .url')
          
          SERVER_DOWNLOAD_URL=$(curl -s "$VERSION_URL" | jq -r '.downloads.server.url')
          
          wget -O "$MINECRAFT_SERVER_JAR" "$SERVER_DOWNLOAD_URL"

      - name: Запуск ngrok для проброса порта
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          unzip ngrok-v3-stable-linux-amd64.tgz

          # Авторизация ngrok
          ./ngrok authtoken $NGROK_AUTH_TOKEN

          # Запуск ngrok в фоновом режиме с пробросом порта 25565 TCP
          ./ngrok tcp 25565 --log=stdout > ngrok.log &

          # Ждем, чтобы туннель установился и получили публичный адрес
          sleep 10

      - name: Получение публичного адреса ngrok
        id: get_ngrok_url
        run: |
          NGROK_URL=$(curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto=="tcp") | .public_url')
          
          echo "ngrok_url=$NGROK_URL" >> $GITHUB_OUTPUT

      - name: Запуск сервера Minecraft в фоновом режиме
        run: |
          cd "$SERVER_DIR"
          
          nohup java -Xmx1024M -Xms1024M -jar "$MINECRAFT_SERVER_JAR" nogui &
          
          echo "Minecraft сервер запущен."

      # Теперь добавим логику ожидания и сохранения файлов за 10 минут до перезагрузки.

      - name: Сохранение логов и файлов перед перезагрузкой
        run: |
          mkdir -p artifacts

          cp ngrok.log artifacts/
          
          cp -r "$SERVER_DIR" artifacts/

      # После этого можно завершить работу сервера и ngrok, чтобы перезапуститься при следующем запуске.
      
      - name: Остановка сервера Minecraft и ngrok перед завершением
        run: |
          # Найти процессы Java и остановить их (или использовать PID-файлы)
          
          pkill -f 'java.*minecraft_server.jar' || true
          
          pkill -f 'ngrok' || true

      # Загружаем артефакты для скачивания после завершения работы.
      
      - name: Сохранить артефакты (логи и файлы)
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-server-logs-and-files
          path: artifacts/
